import {
  Links,
  Meta,
  Outlet,
  Scripts,
  ScrollRestoration,
  useAsyncError,
  useRouteError,
} from 'react-router';

import {
  type CSSProperties,
  Component,
  type ReactNode,
  useCallback,
  useEffect,
  useState,
} from 'react';
import './global.css';

// @ts-expect-error -- virtual module generated by Vite plugin at build time
import { LoadFonts } from 'virtual:load-fonts.jsx';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { Toaster, toast } from 'sonner';
import { AuthProvider } from '../contexts/AuthContext';
import { translate } from '../../../shared/i18n/translate';
import type { Language } from '../../../shared/i18n/translations';
import type { Route } from './+types/root';

// Lives here (not app/layout.jsx) for the same reason AuthProvider does --
// see the comment on <ClientOnly> below -- and because AuthProvider's
// logout needs `useQueryClient()` to clear candidate-sensitive cached data,
// which requires QueryClientProvider to be an ancestor of AuthProvider, not
// a descendant of it.
const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      staleTime: 1000 * 60 * 5, // 5 minutes
      gcTime: 1000 * 60 * 30, // 30 minutes
      retry: (failureCount: number, error: unknown) => {
        const apiError = error as { code?: string; status?: number } | undefined;
        if (apiError?.code === 'NETWORK_ERROR' || apiError?.code === 'TIMEOUT') {
          return failureCount < 2;
        }
        if (typeof apiError?.status === 'number' && apiError.status >= 500) {
          return failureCount < 1;
        }
        return false;
      },
      refetchOnWindowFocus: false,
    },
  },
});

// The crash boundary below intentionally reads the persisted language
// directly from storage, bypassing LanguageContext -- it must still render
// correctly even if the crash originated inside the language provider's own
// subtree.
function readCrashBoundaryLanguage(): Language {
  if (typeof window === 'undefined') return 'en';
  return window.localStorage.getItem('descon.language') === 'ur' ? 'ur' : 'en';
}

export const links = () => [];

const LoadFontsSSR = import.meta.env.SSR ? LoadFonts : null;
if (import.meta.hot) {
  import.meta.hot.on('update-font-links', (urls: string[]) => {
    // remove old font links
    for (const link of document.querySelectorAll('link[data-auto-font]')) {
      link.remove();
    }

    // add new ones
    for (const url of urls) {
      const link = document.createElement('link');
      link.rel = 'stylesheet';
      link.href = url;
      link.dataset.autoFont = 'true';
      document.head.appendChild(link);
    }
  });
}

function InternalErrorBoundary({ error: errorArg }: Route.ErrorBoundaryProps) {
  const routeError = useRouteError();
  const asyncError = useAsyncError();
  const error = errorArg ?? asyncError ?? routeError;
  const [isOpen, setIsOpen] = useState(false);
  const language = readCrashBoundaryLanguage();
  const shouldScale = typeof window !== 'undefined' ? window.innerWidth < 768 : false;
  const scaleFactor = shouldScale ? 1.02 : 1;
  const copyButtonTextClass = shouldScale ? 'text-sm' : 'text-xs';
  const copyButtonPaddingClass = shouldScale ? 'px-[10px] py-[5px]' : 'px-[6px] py-[3px]';

  useEffect(() => {
    console.error(error);
  }, [error]);

  useEffect(() => {
    const animateTimer = setTimeout(() => setIsOpen(true), 100);
    return () => clearTimeout(animateTimer);
  }, []);

  const handleCopyError = useCallback(() => {
    const toastScale = shouldScale ? 1.2 : 1;
    const toastStyle = {
      padding: `${16 * toastScale}px`,
      background: '#18191B',
      border: '1px solid #2C2D2F',
      color: 'white',
      borderRadius: '12px',
      boxShadow: '0 4px 12px rgba(0, 0, 0, 0.1)',
      width: `${280 * toastScale}px`,
      fontSize: `${13 * toastScale}px`,
      display: 'flex',
      alignItems: 'center',
      gap: `${6 * toastScale}px`,
      justifyContent: 'flex-start',
      margin: '0 auto',
    };
    const message = error instanceof Error ? `${error.message}\n\n${error.stack ?? ''}` : String(error);
    navigator.clipboard.writeText(message);
    toast.custom(
      () => (
        <div style={toastStyle}>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 20 20"
            fill="currentColor"
            height="20"
            width="20"
          >
            <title>{translate(language, 'success')}</title>
            <path
              fillRule="evenodd"
              d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.857-9.809a.75.75 0 00-1.214-.882l-3.483 4.79-1.88-1.88a.75.75 0 10-1.06 1.061l2.5 2.5a.75.75 0 001.137-.089l4-5.5z"
              clipRule="evenodd"
            />
          </svg>
          <span>{translate(language, 'copiedSuccessfully')}</span>
        </div>
      ),
      {
        id: 'copy-error-success',
        duration: 3000,
      }
    );
  }, [error, shouldScale]);

  return (
    <div
      className={`fixed bottom-4 left-1/2 transform -translate-x-1/2 max-w-md z-50 transition-all duration-500 ease-out ${
        isOpen ? 'translate-y-0 opacity-100' : 'translate-y-full opacity-0'
      }`}
      style={{ width: '75vw' }}
    >
      <div
        className="bg-[#18191B] text-[#F2F2F2] rounded-lg p-4 shadow-lg w-full"
        style={
          scaleFactor !== 1
            ? ({
                transform: `scale(${scaleFactor})`,
                transformOrigin: 'bottom center',
              } as CSSProperties)
            : undefined
        }
      >
        <div className="flex items-start gap-3">
          <div className="flex-shrink-0">
            <div className="w-8 h-8 bg-[#F2F2F2] rounded-full flex items-center justify-center">
              <span className="text-black text-[1.125rem] leading-none">!</span>
            </div>
          </div>

          <div className="flex flex-col gap-2 flex-1">
            <div className="flex flex-col gap-1">
              <p className="font-light text-[#F2F2F2] text-sm">
                {translate(language, 'appErrorDetected')}
              </p>
              <p className="text-[#959697] text-sm font-light">
                {translate(language, 'appErrorDescription')}
              </p>
            </div>

            <button
              className={`flex flex-row items-center justify-center gap-[4px] outline-none transition-colors rounded-[8px] border-[1px] bg-[#2C2D2F] hover:bg-[#414243] active:bg-[#555658] border-[#414243] text-white ${copyButtonTextClass} ${copyButtonPaddingClass} w-fit`}
              type="button"
              onClick={handleCopyError}
            >
              {translate(language, 'copyErrorAction')}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

type ErrorBoundaryProps = {
  children: React.ReactNode;
};

type ErrorBoundaryState = { hasError: boolean; error: unknown | null };

class ErrorBoundaryWrapper extends Component<ErrorBoundaryProps, ErrorBoundaryState> {
  state: ErrorBoundaryState = { hasError: false, error: null };

  static getDerivedStateFromError(error: unknown): ErrorBoundaryState {
    return { hasError: true, error };
  }

  componentDidCatch(error: unknown, info: unknown) {
    console.error(error, info);
  }

  render() {
    if (this.state.hasError) {
      return <InternalErrorBoundary error={this.state.error} params={{}} />;
    }
    return this.props.children;
  }
}

function LoaderWrapper({ loader }: { loader: () => React.ReactNode }) {
  return <>{loader()}</>;
}

type ClientOnlyProps = {
  loader: () => React.ReactNode;
};

export const ClientOnly: React.FC<ClientOnlyProps> = ({ loader }) => {
  const [isMounted, setIsMounted] = useState(false);

  useEffect(() => {
    setIsMounted(true);
  }, []);

  // ErrorBoundaryWrapper sits outside the isMounted gate so it commits on
  // the first (empty) render and is a stable ancestor by the time children
  // mount. Catastrophic errors (e.g. stack overflow in user code) can blow
  // the call stack before React commits a boundary mounted in the same pass
  // as the throwing child; keeping the boundary always-mounted avoids that.
  return (
    <ErrorBoundaryWrapper>
      {isMounted ? <LoaderWrapper loader={loader} /> : null}
    </ErrorBoundaryWrapper>
  );
};

export function Layout({ children }: { children: ReactNode }) {
  const isMobile = typeof window !== 'undefined' ? window.innerWidth < 768 : false;

  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Descon Manpower</title>
        <Meta />
        <Links />
        <link rel="icon" href="/favicon.png" />
        {LoadFontsSSR ? <LoadFontsSSR /> : null}
      </head>
      <body>
        {/* AuthProvider (and now QueryClientProvider) live here, not in app/layout.jsx
            (like LanguageProvider), because plugins/layouts.ts wraps *every* page.jsx
            with its own fresh copy of layout.jsx's providers -- navigating between
            pages fully unmounts and remounts them. That's invisible for Language (it
            round-trips through localStorage), but silently breaks auth: the in-memory
            session set on OTP success would vanish the instant `navigate()` swapped
            routes. This file (root.tsx) is React Router's actual single, stable root
            -- Layout/ClientOnly are never remounted by navigation -- so this is the
            one place a provider survives it. QueryClientProvider moved up alongside
            it so AuthProvider's logout can call `useQueryClient().clear()` to purge
            candidate-sensitive cached data (AGENTS.md: "Clear sensitive state and
            caches on logout") -- a provider can only use a hook whose provider is an
            ancestor of it, and the reverse nesting doesn't satisfy that. */}
        <ClientOnly
          loader={() => (
            <QueryClientProvider client={queryClient}>
              <AuthProvider>{children}</AuthProvider>
            </QueryClientProvider>
          )}
        />
        <Toaster position={isMobile ? 'top-center' : 'bottom-right'} />
        <ScrollRestoration />
        <Scripts />
      </body>
    </html>
  );
}

export const ErrorBoundary = InternalErrorBoundary;

export default function App() {
  return <Outlet />;
}
